services:
  - docker
language: go
go:
  - "1.12.x"
before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
  - go get golang.org/x/tools/cmd/goimports
  - wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - tar -xzvf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - export PATH=$PATH:$PWD/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
  - sudo sed -i 's/\"registry-mirrors\"/\"insecure-registries\":\[\"172.30.0.0\/16\"], \"registry-mirrors\"/g' /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
  - sudo service docker restart
  - sudo docker info

script:
  - env GO111MODULE=on make lint
  - export LAUNCH_LOCAL_CLUSTER=yes
  - env GO111MODULE=on make test
